# Generated by Django 6.0.1 on 2026-01-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Card', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(default='Standard', max_length=50),
        ),
    ]
