# Generated by Django 6.0.1 on 2026-01-27 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
